### ISSUE TITLE
error occurs

### ISSUE THREAD

**Issue by d4kir92** [HelloWorld017/fileicons-render#2]
Cannot find module 'canvas-prebuilt/canvas/index.js'

this comes on startup of atom

**Comment by d4kir92** [comment]
this is how it looks like

![unbenannt](https://user-images.githubusercontent.com/23246564/35214668-39c1d110-ff62-11e7-87f7-e68b811097ed.png)

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 ia32
**Electron**: 1.6.15
**OS**: D4KIR
**Thrown From**: [fileicons-render](https://github.com/HelloWorld017/fileicons-render) package 1.0.0


### Stack Trace

Failed to load the fileicons-render package

```
At Cannot find module 'canvas-prebuilt/canvas/index.js'

Error: Cannot find module 'canvas-prebuilt/canvas/index.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.3/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:66:33)
    at /packages/fileicons-render-master/index.js:1:193)
    at /packages/fileicons-render-master/index.js:110:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.3/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.23.3/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:937:35)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:618:16)
    at config.transact (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:529:23)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:832:34
```

### Commands

```
```

### Non-Core Packages

```
atom-discord 1.4.0 
file-icons 2.1.16 
fileicons-render 1.0.0 
glua-autocomplete 0.2.2 
language-gmod-lua 0.4.0 
```

**Comment by HelloWorld017** [comment]
fileicons-render is not an atom package. This repository is set of scripts which was used to create icons.
